theme:
  logo:
    gutter: "20px"
  colors:
    primary:
      main: "#F86252"
    text:
      primary: "#3C3C3C"
    typography:
      fontSize: "1rem"
      fontFamily: "Open Sans, sans-serif"
      heading:
        fontWeight: "bold"
